name: Build og Deploy til AWS

on:
  push:
    branches:
      - main
      - '*'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aws-sam-cli

    - name: Build SAM Application
      run: sam build --use-container

    - name: Deploy SAM Application
      if: github.ref == 'refs/heads/main'
      run: |
        sam deploy --guided
