name: SAM Build and Deploy

on:
  push:
    branches:
      - main
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    # AWS Credentials Setup
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
        aws-region: eu-west-1 

    # Build SAM Application
    - name: Build SAM Application
      run: |
        cd eksamen_2023-main/kjell/hello_world
        pip install aws-sam-cli
        sam build

    # Deploy SAM Application
    - name: Deploy SAM Application
      if: github.ref == 'refs/heads/main'
      run: |
        cd eksamen_2023-main/kjell/hello_world
        sam deploy --no-confirm-changeset --stack-name MinSamApplikasjonStack --template-file template.yml


    # Build Docker Image
    - name: Build Docker Image
      run: |
        cd eksamen_2023-main/kjell/hello_world
        docker build -t kjellpy .

    # run the Docker container
    - name: Run Docker Container
      run: |
        docker run \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} \
          -e BUCKET_NAME=kjellsimgebucket2032 \
          kjellpy

